version: 0.2

# env variables passed from Terraform/CodeBuild project config:
# - ENV_NAME, PROJECT_PREFIX, AWS_DEFAULT_REGION, AWS_ACCOUNT_ID
# - NODEJS_VERSION, BUILD_CONFIG, SERVICE_NAME, SOURCE_PATH, IMAGE_REPO_NAME
# - TASK_CPU, TASK_MEMORY, CONTAINER_PORT, CONTAINER_NAME
# - TASK_FAMILY, TASK_EXECUTION_ROLE, TASK_ROLE

cache:
  paths:
    - 'src/Frontend/node_modules/**/*'
    - 'src/Frontend/.next/cache/**/*'

phases:
  install:
    runtime-versions:
      nodejs: ${NODEJS_VERSION}
  
  pre_build:
    commands:
      - echo "Building $SERVICE_NAME Service..."
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG="v1.0.${CODEBUILD_BUILD_NUMBER:-1}-${COMMIT_HASH}"
      - echo "Image tag:$IMAGE_TAG"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - cd $SOURCE_PATH
      - npm ci || npm install
  
  build:
    commands:
      - npm run build
      - npm run test || echo "No tests configured"
      - cd ../..
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG -f ${SOURCE_PATH}Dockerfile $SOURCE_PATH
      - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  
  post_build:
    commands:
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - export IMAGE_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      
      - echo "Tracking deployment..."
      - DEPLOYMENT_INFO="{\"service\":\"$SERVICE_NAME\",\"image_tag\":\"$IMAGE_TAG\",\"deployed_at\":\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\",\"commit\":\"$COMMIT_HASH\"}"
      - aws ssm put-parameter --name "/${PROJECT_PREFIX}/${ENV_NAME}/deployments/${SERVICE_NAME}/latest" --value "$DEPLOYMENT_INFO" --type String --overwrite
      
      - echo "Updating task definition..."
      - envsubst < taskdef-frontend-template.json > taskdef.json
      - jq 'del(.taskDefinitionArn,.revision,.status,.requiresAttributes,.compatibilities,.registeredAt,.registeredBy,.tags) | .containerDefinitions[0].image="'$IMAGE_URI'" | .containerDefinitions[0].portMappings[0].containerPort=(.containerDefinitions[0].portMappings[0].containerPort|tonumber) | .cpu=(.cpu|tostring) | .memory=(.memory|tostring)' taskdef.json > taskdef_tmp.json
      - mv taskdef_tmp.json taskdef.json
      - NEW_TASK_DEF_ARN=$(aws ecs register-task-definition --cli-input-json file://taskdef.json --query 'taskDefinition.taskDefinitionArn' --output text)
      - echo "Task Definition:$NEW_TASK_DEF_ARN"
      - sed -i "s|<TASK_DEFINITION>|$NEW_TASK_DEF_ARN|g" appspec.yml
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $IMAGE_URI > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
    - taskdef.json
    - appspec.yml
